"""
End to end: PR trigger -> graph -> formatted PR review comment.

This is the closest thing to your diagram's full flow, minus the parts
that need real cloud infra (GitHub webhook, Azure AI Search RAG, MCP
tool registry — see README.md "Next steps" for how to add those).

Run:
    python3 main.py

Requires ANTHROPIC_API_KEY set (copy .env.example -> .env and fill it in).
"""

import asyncio

from graph import graph, load_pr
from langgraph.types import Command


def format_pr_comment(payload: dict) -> str:
    """Mimics diagram box: 'AI posts Review in Pull Request'."""
    lines = [
        "## 🤖 Agentic AI DevSecOps Review",
        "",
        f"**Risk classification:** `{payload['risk_level'].upper()}`",
        "",
        "### Root cause",
        payload["root_cause"],
        "",
        "### Recommendations",
    ]
    for r in payload["recommendations"]:
        lines.append(f"- [ ] {r}")
    lines.append("")
    lines.append("_This is a mock review — no LLM call in dry-run mode._" if payload.get("_mock") else
                  "_Generated by the Agentic AI Orchestrator (LangGraph + Claude)._")
    return "\n".join(lines)


async def run(pr_path: str = "mock_data/sample_pr.json"):
    pr = load_pr(pr_path)
    config = {"configurable": {"thread_id": f"pr-{pr['pr_number']}"}}

    print(f"📥 PR trigger received: #{pr['pr_number']} — {pr['pr_title']}")
    print(f"   Changed files: {pr['changed_files']}\n")

    result = await graph.ainvoke({
        "pr_title": pr["pr_title"],
        "pr_number": pr["pr_number"],
        "changed_files": pr["changed_files"],
        "agent_results": [],
        "root_cause": "",
        "risk_level": "",
        "recommendations": [],
        "final_decision": "",
    }, config=config)

    if "__interrupt__" in result:
        payload = result["__interrupt__"][0].value
        comment = format_pr_comment(payload)
        print("=" * 60)
        print("POSTED PR COMMENT (would be posted via GitHub/Azure DevOps API):")
        print("=" * 60)
        print(comment)
        print("=" * 60)

        # In real life this comes from a human clicking Approve/Reject on
        # the PR, a Slack button, or a CAB ticket closing. Here we simulate it.
        decision = input(
            "\nType a decision to resume the graph (e.g. 'approved', 'rejected'): "
        ).strip() or "approved"

        final = await graph.ainvoke(Command(resume=decision), config=config)
        print(f"\n✅ Final decision recorded: {final['final_decision']}")
    else:
        print(f"✅ Auto-merged (risk=low). Final decision: {result['final_decision']}")


if __name__ == "__main__":
    asyncio.run(run())
