"""post_summary_node: the CI graph's terminal node (see ci_graph.py). Posts
synthesis_node's structured review as a PR comment via the GitHub MCP's
add_issue_comment tool (issue_number == PR number for GitHub's API) — no
interrupt, no auto-merge, a human reviews and merges via GitHub's own UI."""

import asyncio
import os

from dotenv import load_dotenv
from langchain_mcp_adapters.client import MultiServerMCPClient

load_dotenv()

GITHUB_MCP_URL = "https://api.githubcopilot.com/mcp/"


def format_summary_comment(state) -> str:
    lines = [
        "## 🤖 Agentic AI DevSecOps Review",
        "",
        f"**Risk classification:** `{state['risk_level'].upper()}`",
        "",
        "### Root cause",
        state["root_cause"],
        "",
        "### Recommendations",
    ]
    for r in state["recommendations"]:
        lines.append(f"- [ ] {r}")
    lines.append("")
    lines.append("_Generated by the Agentic AI Orchestrator (LangGraph + Claude, run as a Temporal Workflow)._")
    return "\n".join(lines)


async def _post_comment(owner: str, repo: str, pr_number: int, token: str, body: str) -> None:
    client = MultiServerMCPClient({
        "github": {
            "transport": "streamable_http",
            "url": GITHUB_MCP_URL,
            "headers": {"Authorization": f"Bearer {token}"},
        }
    })
    tools = {t.name: t for t in await client.get_tools()}
    result = await tools["add_issue_comment"].ainvoke({
        "owner": owner,
        "repo": repo,
        "issue_number": pr_number,
        "body": body,
    })
    # GitHub's MCP server relays upstream API errors (bad/under-scoped token,
    # repo not found, etc.) as normal tool-result text rather than an MCP
    # protocol-level error — a call can "succeed" here while actually having
    # posted nothing. Catch that instead of silently reporting success.
    text = result[0]["text"] if isinstance(result, list) and result else str(result)
    if any(marker in text for marker in ("Not Found", "not accessible", '"status": "403"', '"status": "404"')):
        raise RuntimeError(f"GitHub MCP add_issue_comment returned an error: {text[:300]}")


def post_summary_node(state) -> dict:
    comment = format_summary_comment(state)
    repo_full = os.environ.get("GITHUB_REPO")
    token = os.environ.get("GITHUB_TOKEN")

    if not repo_full or not token:
        print("[post_summary] GITHUB_REPO/GITHUB_TOKEN not configured — printing instead of posting.")
        print(comment)
        return {"final_decision": "summary-generated (not posted — GitHub not configured)"}

    owner, repo = repo_full.split("/", 1)
    print(f"[post_summary] posting review comment to {repo_full}#{state['pr_number']} via GitHub MCP...")
    try:
        asyncio.run(_post_comment(owner, repo, state["pr_number"], token, comment))
    except Exception as e:
        print(f"[post_summary] GitHub MCP call failed ({e}) — printing instead.")
        print(comment)
        return {"final_decision": f"summary-generated (post failed: {e})"}

    return {"final_decision": "summary-posted-to-pr"}
